services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8080 --reload
    environment:
      - PYTHONPATH=/app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
      - ./tmp:/tmp
    working_dir: /app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8080
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
